### ISSUE TITLE
版本控制系统写反了吧

### ISSUE THREAD

**Issue by alucardpj** [monklof/Back-End-Developer-Interview-Questions#1]
(注:分散式版本控制系统: Centralized Version Control Systems；集中式版本控制系统: Distributed Version Control Systems)

这个写反了吧

**Comment by monklof** [comment]
多谢提醒，已经修正，还有其他的问题吗？

**Comment by alucardpj** [comment]
粗看一遍发现这个，还没有仔细看是不是有其他的

**Comment by monklof** [comment]
@alucardpj 好的，多谢。还有问题请随意提出来。
