### ISSUE TITLE
network partitions的翻译问题

### ISSUE THREAD

**Issue by rhinenoir** [monklof/Back-End-Developer-Interview-Questions#3]
network partitions 文中翻译成了网络分裂，但是不是翻译成网络分区会更好些？cap原则中的p是partition tolerance，一般中文是翻译成分区容错性的:kissing:

_Sent from my PRO 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by monklof** [comment]
欢迎提PR~

**Comment by rhinenoir** [comment]
@monklof 已提，求审核

_Sent from my PRO 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
